# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  forgejo:
    taskfile: ./forgejo
    optional: true

  # ===========================================================
  # Deprecated
  #   Use the fully open source fork forgejo container instead.
  # ===========================================================

  # gitea:
  #   taskfile: ./gitea
  #   optional: true
