# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  ENGINE:
    sh: |
      if command -v podman > /dev/null; then
        echo -n "podman"
      elif command -v docker > /dev/null; then
        echo -n "docker"
      else
        exit 1
      fi

tasks:
  up:
    desc: Compose up forgejo containers
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - "{{.ENGINE}} compose up -d"

  down:
    desc: Compose down forgejo containers
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - "{{.ENGINE}} compose down 2> /dev/null"
    silent: true

  clean:
    desc: Remove containers and volumes
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - "{{.ENGINE}} compose down -v 2> /dev/null"
    silent: true
