# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  ENGINE:
    sh: |
      if command -v podman > /dev/null; then
        echo -n "podman"
      elif command -v docker > /dev/null; then
        echo -n "docker"
      fi

tasks:
  up:
    desc: Start Kafka broker container
    dir: "{{.TASKFILE_DIR}}"
    preconditions:
      - sh: test -n "{{.ENGINE}}"
        msg: Podman or Docker needed.
    cmds:
      - "{{.ENGINE}} compose up -d"
    silent: true

  down:
    desc: Shutdown Kafka broker container
    dir: "{{.TASKFILE_DIR}}"
    preconditions:
      - sh: test -n "{{.ENGINE}}"
        msg: Podman or Docker needed.
    cmds:
      - "{{.ENGINE}} compose down > /dev/null"
    silent: true

  shell:
    desc: Open kafka broker shell
    dir: "{{.TASKFILE_DIR}}"
    preconditions:
      - sh: test -n "{{.ENGINE}}"
        msg: Podman or Docker needed.
    cmds:
      - "{{.ENGINE}} exec --workdir /opt/kafka/bin/ -it tutorial-kafka sh"
    silent: true
    interactive: true
